[workspace]
members = [
    "apps/lst-gpui",
    "crates/lst-editor",
    "crates/lst-x11-harness",
]
default-members = [
    "apps/lst-gpui",
    "crates/lst-editor",
]
resolver = "2"

[workspace.dependencies]
modalkit = { version = "=0.0.25", default-features = false }
regex = "1.11"
ropey = "1.6.1"
unicode-segmentation = "1.12"

[profile.release]
opt-level = 3
lto = true
strip = true
