use gpui::KeyBinding;

use crate::{
    Backspace, CloseActiveTab, CopySelection, CutSelection, DeleteForward, DeleteLine,
    DuplicateLine, FindNext, FindOpen, FindOpenReplace, FindPrev, GotoLineOpen, InsertNewline,
    InsertTab, MoveDocumentEnd, MoveDocumentStart, MoveDown, MoveLeft, MoveLineDown, MoveLineEnd,
    MoveLineStart, MoveLineUp, MovePageDown, MovePageUp, MoveRight, MoveUp, MoveWordLeft,
    MoveWordRight, NewTab, NextTab, OpenFile, PasteClipboard, PrevTab, Quit, Redo, SaveFile,
    SaveFileAs, SelectAll, SelectDocumentEnd, SelectDocumentStart, SelectDown, SelectLeft,
    SelectLineEnd, SelectLineStart, SelectPageDown, SelectPageUp, SelectRight, SelectUp,
    SelectWordLeft, SelectWordRight, ToggleComment, ToggleWrap, Undo,
};

pub(crate) fn editor_keybindings() -> Vec<KeyBinding> {
    vec![
        KeyBinding::new("ctrl-n", NewTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-n", NewTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("ctrl-o", OpenFile, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-o", OpenFile, Some("Workspace && !InlineInput")),
        KeyBinding::new("ctrl-s", SaveFile, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-s", SaveFile, Some("Workspace && !InlineInput")),
        KeyBinding::new(
            "ctrl-shift-s",
            SaveFileAs,
            Some("Workspace && !InlineInput"),
        ),
        KeyBinding::new("cmd-shift-s", SaveFileAs, Some("Workspace && !InlineInput")),
        KeyBinding::new("ctrl-w", CloseActiveTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-w", CloseActiveTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("ctrl-tab", NextTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-shift-]", NextTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("ctrl-shift-tab", PrevTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-shift-[", PrevTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("alt-z", ToggleWrap, Some("Workspace && !InlineInput")),
        KeyBinding::new("ctrl-c", CopySelection, Some("Editor")),
        KeyBinding::new("cmd-c", CopySelection, Some("Editor")),
        KeyBinding::new("ctrl-x", CutSelection, Some("Editor")),
        KeyBinding::new("cmd-x", CutSelection, Some("Editor")),
        KeyBinding::new("ctrl-v", PasteClipboard, Some("Editor")),
        KeyBinding::new("cmd-v", PasteClipboard, Some("Editor")),
        KeyBinding::new("ctrl-z", Undo, Some("Editor")),
        KeyBinding::new("cmd-z", Undo, Some("Editor")),
        KeyBinding::new("ctrl-y", Redo, Some("Editor")),
        KeyBinding::new("cmd-shift-z", Redo, Some("Editor")),
        KeyBinding::new("ctrl-f", FindOpen, Some("Workspace")),
        KeyBinding::new("cmd-f", FindOpen, Some("Workspace")),
        KeyBinding::new("ctrl-h", FindOpenReplace, Some("Workspace")),
        KeyBinding::new("cmd-h", FindOpenReplace, Some("Workspace")),
        KeyBinding::new("f3", FindNext, Some("Workspace")),
        KeyBinding::new("shift-f3", FindPrev, Some("Workspace")),
        KeyBinding::new("ctrl-g", GotoLineOpen, Some("Workspace")),
        KeyBinding::new("cmd-g", GotoLineOpen, Some("Workspace")),
        KeyBinding::new("alt-up", MoveLineUp, Some("Editor")),
        KeyBinding::new("alt-down", MoveLineDown, Some("Editor")),
        KeyBinding::new("ctrl-shift-k", DeleteLine, Some("Editor")),
        KeyBinding::new("cmd-shift-k", DeleteLine, Some("Editor")),
        KeyBinding::new("ctrl-shift-d", DuplicateLine, Some("Editor")),
        KeyBinding::new("cmd-shift-d", DuplicateLine, Some("Editor")),
        KeyBinding::new("ctrl-/", ToggleComment, Some("Editor")),
        KeyBinding::new("cmd-/", ToggleComment, Some("Editor")),
        KeyBinding::new("left", MoveLeft, Some("Editor")),
        KeyBinding::new("right", MoveRight, Some("Editor")),
        KeyBinding::new("ctrl-left", MoveWordLeft, Some("Editor")),
        KeyBinding::new("ctrl-right", MoveWordRight, Some("Editor")),
        KeyBinding::new("alt-left", MoveWordLeft, Some("Editor")),
        KeyBinding::new("alt-right", MoveWordRight, Some("Editor")),
        KeyBinding::new("up", MoveUp, Some("Editor")),
        KeyBinding::new("down", MoveDown, Some("Editor")),
        KeyBinding::new("pageup", MovePageUp, Some("Editor")),
        KeyBinding::new("pagedown", MovePageDown, Some("Editor")),
        KeyBinding::new("ctrl-home", MoveDocumentStart, Some("Editor")),
        KeyBinding::new("ctrl-end", MoveDocumentEnd, Some("Editor")),
        KeyBinding::new("cmd-up", MoveDocumentStart, Some("Editor")),
        KeyBinding::new("cmd-down", MoveDocumentEnd, Some("Editor")),
        KeyBinding::new("shift-left", SelectLeft, Some("Editor")),
        KeyBinding::new("shift-right", SelectRight, Some("Editor")),
        KeyBinding::new("ctrl-shift-left", SelectWordLeft, Some("Editor")),
        KeyBinding::new("ctrl-shift-right", SelectWordRight, Some("Editor")),
        KeyBinding::new("alt-shift-left", SelectWordLeft, Some("Editor")),
        KeyBinding::new("alt-shift-right", SelectWordRight, Some("Editor")),
        KeyBinding::new("shift-up", SelectUp, Some("Editor")),
        KeyBinding::new("shift-down", SelectDown, Some("Editor")),
        KeyBinding::new("ctrl-up", SelectUp, Some("Editor")),
        KeyBinding::new("ctrl-down", SelectDown, Some("Editor")),
        KeyBinding::new("shift-pageup", SelectPageUp, Some("Editor")),
        KeyBinding::new("shift-pagedown", SelectPageDown, Some("Editor")),
        KeyBinding::new("ctrl-shift-home", SelectDocumentStart, Some("Editor")),
        KeyBinding::new("ctrl-shift-end", SelectDocumentEnd, Some("Editor")),
        KeyBinding::new("cmd-shift-up", SelectDocumentStart, Some("Editor")),
        KeyBinding::new("cmd-shift-down", SelectDocumentEnd, Some("Editor")),
        KeyBinding::new("home", MoveLineStart, Some("Editor")),
        KeyBinding::new("end", MoveLineEnd, Some("Editor")),
        KeyBinding::new("shift-home", SelectLineStart, Some("Editor")),
        KeyBinding::new("shift-end", SelectLineEnd, Some("Editor")),
        KeyBinding::new("backspace", Backspace, Some("Editor")),
        KeyBinding::new("delete", DeleteForward, Some("Editor")),
        KeyBinding::new("enter", InsertNewline, Some("Editor")),
        KeyBinding::new("tab", InsertTab, Some("Editor")),
        KeyBinding::new("ctrl-a", SelectAll, Some("Editor")),
        KeyBinding::new("cmd-a", SelectAll, Some("Editor")),
        KeyBinding::new("ctrl-q", Quit, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-q", Quit, Some("Workspace && !InlineInput")),
    ]
}
