use gpui::KeyBinding;

use crate::{
    Backspace, CloseActiveTab, CopySelection, CutSelection, DeleteForward, DeleteLine,
    DeleteWordBackward, DeleteWordForward, DuplicateLine, FindNext, FindOpen, FindOpenReplace,
    FindPrev, GotoLineOpen, InsertNewline, InsertTab, MoveDocumentEnd, MoveDocumentStart, MoveDown,
    MoveLeft, MoveLineDown, MoveLineEnd, MoveLineStart, MoveLineUp, MovePageDown, MovePageUp,
    MoveRight, MoveSmartHome, MoveSubwordLeft, MoveSubwordRight, MoveUp, MoveWordLeft,
    MoveWordRight, NewTab, NextTab, OpenFile, OutdentSelection, PasteClipboard, PrevTab, Quit,
    Redo, SaveFile, SaveFileAs, SelectAll, SelectDocumentEnd, SelectDocumentStart, SelectDown,
    SelectLeft, SelectLineEnd, SelectLineStart, SelectPageDown, SelectPageUp, SelectRight,
    SelectSmartHome, SelectSubwordLeft, SelectSubwordRight, SelectUp, SelectWordLeft,
    SelectWordRight, ToggleComment, ToggleWrap, Undo, ZoomIn, ZoomOut, ZoomReset,
};

const EDITOR_CONTEXT: &str = "Editor && !InlineInput";

pub(crate) fn editor_keybindings() -> Vec<KeyBinding> {
    vec![
        KeyBinding::new("ctrl-n", NewTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-n", NewTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("ctrl-o", OpenFile, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-o", OpenFile, Some("Workspace && !InlineInput")),
        KeyBinding::new("ctrl-s", SaveFile, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-s", SaveFile, Some("Workspace && !InlineInput")),
        KeyBinding::new(
            "ctrl-shift-s",
            SaveFileAs,
            Some("Workspace && !InlineInput"),
        ),
        KeyBinding::new("cmd-shift-s", SaveFileAs, Some("Workspace && !InlineInput")),
        KeyBinding::new("ctrl-w", CloseActiveTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-w", CloseActiveTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("ctrl-tab", NextTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-shift-]", NextTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("ctrl-shift-tab", PrevTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-shift-[", PrevTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("alt-z", ToggleWrap, Some("Workspace && !InlineInput")),
        KeyBinding::new("ctrl-=", ZoomIn, Some("Workspace")),
        KeyBinding::new("ctrl-+", ZoomIn, Some("Workspace")),
        KeyBinding::new("cmd-=", ZoomIn, Some("Workspace")),
        KeyBinding::new("cmd-+", ZoomIn, Some("Workspace")),
        KeyBinding::new("ctrl--", ZoomOut, Some("Workspace")),
        KeyBinding::new("cmd--", ZoomOut, Some("Workspace")),
        KeyBinding::new("ctrl-0", ZoomReset, Some("Workspace")),
        KeyBinding::new("cmd-0", ZoomReset, Some("Workspace")),
        KeyBinding::new("ctrl-c", CopySelection, Some(EDITOR_CONTEXT)),
        KeyBinding::new("cmd-c", CopySelection, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-x", CutSelection, Some(EDITOR_CONTEXT)),
        KeyBinding::new("cmd-x", CutSelection, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-v", PasteClipboard, Some(EDITOR_CONTEXT)),
        KeyBinding::new("cmd-v", PasteClipboard, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-z", Undo, Some(EDITOR_CONTEXT)),
        KeyBinding::new("cmd-z", Undo, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-y", Redo, Some(EDITOR_CONTEXT)),
        KeyBinding::new("cmd-shift-z", Redo, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-f", FindOpen, Some("Workspace")),
        KeyBinding::new("cmd-f", FindOpen, Some("Workspace")),
        KeyBinding::new("ctrl-h", FindOpenReplace, Some("Workspace")),
        KeyBinding::new("cmd-h", FindOpenReplace, Some("Workspace")),
        KeyBinding::new("f3", FindNext, Some("Workspace")),
        KeyBinding::new("shift-f3", FindPrev, Some("Workspace")),
        KeyBinding::new("ctrl-g", GotoLineOpen, Some("Workspace")),
        KeyBinding::new("cmd-g", GotoLineOpen, Some("Workspace")),
        KeyBinding::new("alt-up", MoveLineUp, Some(EDITOR_CONTEXT)),
        KeyBinding::new("alt-down", MoveLineDown, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-shift-k", DeleteLine, Some(EDITOR_CONTEXT)),
        KeyBinding::new("cmd-shift-k", DeleteLine, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-shift-d", DuplicateLine, Some(EDITOR_CONTEXT)),
        KeyBinding::new("cmd-shift-d", DuplicateLine, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-/", ToggleComment, Some(EDITOR_CONTEXT)),
        KeyBinding::new("cmd-/", ToggleComment, Some(EDITOR_CONTEXT)),
        KeyBinding::new("left", MoveLeft, Some(EDITOR_CONTEXT)),
        KeyBinding::new("right", MoveRight, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-left", MoveWordLeft, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-right", MoveWordRight, Some(EDITOR_CONTEXT)),
        KeyBinding::new("alt-left", MoveSubwordLeft, Some(EDITOR_CONTEXT)),
        KeyBinding::new("alt-right", MoveSubwordRight, Some(EDITOR_CONTEXT)),
        KeyBinding::new("up", MoveUp, Some(EDITOR_CONTEXT)),
        KeyBinding::new("down", MoveDown, Some(EDITOR_CONTEXT)),
        KeyBinding::new("pageup", MovePageUp, Some(EDITOR_CONTEXT)),
        KeyBinding::new("pagedown", MovePageDown, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-home", MoveDocumentStart, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-end", MoveDocumentEnd, Some(EDITOR_CONTEXT)),
        KeyBinding::new("cmd-up", MoveDocumentStart, Some(EDITOR_CONTEXT)),
        KeyBinding::new("cmd-down", MoveDocumentEnd, Some(EDITOR_CONTEXT)),
        KeyBinding::new("shift-left", SelectLeft, Some(EDITOR_CONTEXT)),
        KeyBinding::new("shift-right", SelectRight, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-shift-left", SelectWordLeft, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-shift-right", SelectWordRight, Some(EDITOR_CONTEXT)),
        KeyBinding::new("alt-shift-left", SelectSubwordLeft, Some(EDITOR_CONTEXT)),
        KeyBinding::new("alt-shift-right", SelectSubwordRight, Some(EDITOR_CONTEXT)),
        KeyBinding::new("shift-up", SelectUp, Some(EDITOR_CONTEXT)),
        KeyBinding::new("shift-down", SelectDown, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-up", SelectUp, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-down", SelectDown, Some(EDITOR_CONTEXT)),
        KeyBinding::new("shift-pageup", SelectPageUp, Some(EDITOR_CONTEXT)),
        KeyBinding::new("shift-pagedown", SelectPageDown, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-shift-home", SelectDocumentStart, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-shift-end", SelectDocumentEnd, Some(EDITOR_CONTEXT)),
        KeyBinding::new("cmd-shift-up", SelectDocumentStart, Some(EDITOR_CONTEXT)),
        KeyBinding::new("cmd-shift-down", SelectDocumentEnd, Some(EDITOR_CONTEXT)),
        KeyBinding::new("home", MoveSmartHome, Some(EDITOR_CONTEXT)),
        KeyBinding::new("end", MoveLineEnd, Some(EDITOR_CONTEXT)),
        KeyBinding::new("cmd-left", MoveLineStart, Some(EDITOR_CONTEXT)),
        KeyBinding::new("cmd-right", MoveLineEnd, Some(EDITOR_CONTEXT)),
        KeyBinding::new("shift-home", SelectSmartHome, Some(EDITOR_CONTEXT)),
        KeyBinding::new("shift-end", SelectLineEnd, Some(EDITOR_CONTEXT)),
        KeyBinding::new("cmd-shift-left", SelectLineStart, Some(EDITOR_CONTEXT)),
        KeyBinding::new("cmd-shift-right", SelectLineEnd, Some(EDITOR_CONTEXT)),
        KeyBinding::new("backspace", Backspace, Some(EDITOR_CONTEXT)),
        KeyBinding::new("delete", DeleteForward, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-backspace", DeleteWordBackward, Some(EDITOR_CONTEXT)),
        KeyBinding::new("alt-backspace", DeleteWordBackward, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-delete", DeleteWordForward, Some(EDITOR_CONTEXT)),
        KeyBinding::new("alt-delete", DeleteWordForward, Some(EDITOR_CONTEXT)),
        KeyBinding::new("enter", InsertNewline, Some(EDITOR_CONTEXT)),
        KeyBinding::new("tab", InsertTab, Some(EDITOR_CONTEXT)),
        KeyBinding::new("shift-tab", OutdentSelection, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-a", SelectAll, Some(EDITOR_CONTEXT)),
        KeyBinding::new("cmd-a", SelectAll, Some(EDITOR_CONTEXT)),
        KeyBinding::new("ctrl-q", Quit, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-q", Quit, Some("Workspace && !InlineInput")),
    ]
}
