use gpui::KeyBinding;

use crate::{
    Backspace, CloseActiveTab, CopySelection, CutSelection, DeleteForward, DeleteLine,
    DuplicateLine, FindNext, FindOpen, FindOpenReplace, FindPrev, GotoLineOpen, InsertNewline,
    InsertTab, MoveDown, MoveLeft, MoveLineDown, MoveLineEnd, MoveLineStart, MoveLineUp, MoveRight,
    MoveUp, NewTab, NextTab, OpenFile, PasteClipboard, PrevTab, Quit, Redo, SaveFile, SaveFileAs,
    SelectAll, SelectDown, SelectLeft, SelectLineEnd, SelectLineStart, SelectRight, SelectUp,
    ToggleComment, ToggleWrap, Undo,
};

pub(crate) fn editor_keybindings() -> Vec<KeyBinding> {
    vec![
        KeyBinding::new("ctrl-n", NewTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-n", NewTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("ctrl-o", OpenFile, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-o", OpenFile, Some("Workspace && !InlineInput")),
        KeyBinding::new("ctrl-s", SaveFile, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-s", SaveFile, Some("Workspace && !InlineInput")),
        KeyBinding::new(
            "ctrl-shift-s",
            SaveFileAs,
            Some("Workspace && !InlineInput"),
        ),
        KeyBinding::new("cmd-shift-s", SaveFileAs, Some("Workspace && !InlineInput")),
        KeyBinding::new("ctrl-w", CloseActiveTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-w", CloseActiveTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("ctrl-tab", NextTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-shift-]", NextTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("ctrl-shift-tab", PrevTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-shift-[", PrevTab, Some("Workspace && !InlineInput")),
        KeyBinding::new("alt-z", ToggleWrap, Some("Workspace && !InlineInput")),
        KeyBinding::new("ctrl-c", CopySelection, Some("Editor")),
        KeyBinding::new("cmd-c", CopySelection, Some("Editor")),
        KeyBinding::new("ctrl-x", CutSelection, Some("Editor")),
        KeyBinding::new("cmd-x", CutSelection, Some("Editor")),
        KeyBinding::new("ctrl-v", PasteClipboard, Some("Editor")),
        KeyBinding::new("cmd-v", PasteClipboard, Some("Editor")),
        KeyBinding::new("ctrl-z", Undo, Some("Editor")),
        KeyBinding::new("cmd-z", Undo, Some("Editor")),
        KeyBinding::new("ctrl-y", Redo, Some("Editor")),
        KeyBinding::new("cmd-shift-z", Redo, Some("Editor")),
        KeyBinding::new("ctrl-f", FindOpen, Some("Workspace")),
        KeyBinding::new("cmd-f", FindOpen, Some("Workspace")),
        KeyBinding::new("ctrl-h", FindOpenReplace, Some("Workspace")),
        KeyBinding::new("cmd-h", FindOpenReplace, Some("Workspace")),
        KeyBinding::new("f3", FindNext, Some("Workspace")),
        KeyBinding::new("shift-f3", FindPrev, Some("Workspace")),
        KeyBinding::new("ctrl-g", GotoLineOpen, Some("Workspace")),
        KeyBinding::new("cmd-g", GotoLineOpen, Some("Workspace")),
        KeyBinding::new("alt-up", MoveLineUp, Some("Editor")),
        KeyBinding::new("alt-down", MoveLineDown, Some("Editor")),
        KeyBinding::new("ctrl-shift-k", DeleteLine, Some("Editor")),
        KeyBinding::new("cmd-shift-k", DeleteLine, Some("Editor")),
        KeyBinding::new("ctrl-shift-d", DuplicateLine, Some("Editor")),
        KeyBinding::new("cmd-shift-d", DuplicateLine, Some("Editor")),
        KeyBinding::new("ctrl-/", ToggleComment, Some("Editor")),
        KeyBinding::new("cmd-/", ToggleComment, Some("Editor")),
        KeyBinding::new("left", MoveLeft, Some("Editor")),
        KeyBinding::new("right", MoveRight, Some("Editor")),
        KeyBinding::new("up", MoveUp, Some("Editor")),
        KeyBinding::new("down", MoveDown, Some("Editor")),
        KeyBinding::new("shift-left", SelectLeft, Some("Editor")),
        KeyBinding::new("shift-right", SelectRight, Some("Editor")),
        KeyBinding::new("shift-up", SelectUp, Some("Editor")),
        KeyBinding::new("shift-down", SelectDown, Some("Editor")),
        KeyBinding::new("ctrl-up", SelectUp, Some("Editor")),
        KeyBinding::new("ctrl-down", SelectDown, Some("Editor")),
        KeyBinding::new("home", MoveLineStart, Some("Editor")),
        KeyBinding::new("end", MoveLineEnd, Some("Editor")),
        KeyBinding::new("shift-home", SelectLineStart, Some("Editor")),
        KeyBinding::new("shift-end", SelectLineEnd, Some("Editor")),
        KeyBinding::new("backspace", Backspace, Some("Editor")),
        KeyBinding::new("delete", DeleteForward, Some("Editor")),
        KeyBinding::new("enter", InsertNewline, Some("Editor")),
        KeyBinding::new("tab", InsertTab, Some("Editor")),
        KeyBinding::new("ctrl-a", SelectAll, Some("Editor")),
        KeyBinding::new("cmd-a", SelectAll, Some("Editor")),
        KeyBinding::new("ctrl-q", Quit, Some("Workspace && !InlineInput")),
        KeyBinding::new("cmd-q", Quit, Some("Workspace && !InlineInput")),
    ]
}
